<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/24 11:16:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hrm_kenya',
  'username' => 'hrmkenya',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
